import React, { useContext } from 'react';
import Head from 'next/head';
import { AppContext } from '../context/AppContext';
import { Order } from '../modules/Order/Order';
import { User } from '../modules/User/User';

export default function Home() {
  const { isActiveButton, orders, isLoading, getData, getUser, users } = useContext(AppContext);
  return (
    <div>
      <Head>
        <title>CRM - Gastro Shef</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="container">
        {isActiveButton === "Заказы" && (
          <Order orders={orders} isLoading={isLoading} getData={getData} />
        )}
        {isActiveButton === "Клиенты" && (
          <User users={users} isLoading={isLoading} getUser={getUser} />
        )}
      </div>
    </div>
  );
}