/* eslint-disable react-hooks/exhaustive-deps */
import Head from "next/head";
import React, { useEffect, useContext } from "react";
import { Order } from "../../modules/Order/Order";
import { AppContext } from "../../context/AppContext";

export default function OrderPage() {
  const { orders, getData, isLoading } = useContext(AppContext);

  useEffect(() => {
    getData();
  }, []);

  return (
    <div>
      <Head>
        <title>CRM - Gastro Shef</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="container">
        <Order orders={orders} isLoading={isLoading} getData={getData} />
      </div>
    </div>
  );
}
