/* eslint-disable react-hooks/exhaustive-deps */
import Head from "next/head";
import React, { useEffect, useContext } from "react";
import { User } from "../../modules/User/User";
import { AppContext } from "../../context/AppContext";

export default function UserPage() {
  const { users, getUser, isLoading } = useContext(AppContext);

  useEffect(() => {
    getUser();
  }, []);

  return (
    <div>
      <Head>
        <title>User - Gastro Shef</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="container">
        {/* <User users={users} isLoading={isLoading} getUser={getUser} /> */}
        <User users={users} isLoading={isLoading} getUser={getUser} />
      </div>
    </div>
  );
}
